Dev
maksar24/frontend-kapusta pull request #25
Opened 2022-01-21 05:04 UTC by Zhdanov-Eugene

первий коммит

2022-01-21 06:43 UTC, Zhdanov-Eugene commented
всі інші зміни запулив

2022-01-21 09:57 UTC, maksar24 requested changes

2022-01-21 09:57 UTC, maksar24 commented on .netlify/state.json
> +{
не нужный файл, удали

2022-01-21 09:57 UTC, maksar24 commented on jsconfig.json
> +{
не нужный файл, удали

2022-01-21 09:57 UTC, maksar24 commented on netlify.toml
> +[build]
не нужный файл, удали

2022-01-21 09:57 UTC, maksar24 commented on src/App.css
> +.title {
не нужный файл, удали

2022-01-21 09:57 UTC, maksar24 commented on package.json
> +    "eject": "react-scripts eject",
эта +40 и 41 строки пока не нужны, удали их

2022-01-21 09:57 UTC, maksar24 commented on src/App.js
> +import React, { Suspense, /*lazy,*/ useEffect } from 'react';
оставь этот файл у себя таким каким он был изначально, он у нас в ветке dev уже давно начат и имеет другой вид

2022-01-21 09:57 UTC, maksar24 commented on README.md
> +#Создать модалку при нулевом балансе
удали эти две строки, ничего лишнего не оставляй в это файле, я его потом оформлять буду

2022-01-21 09:57 UTC, maksar24 commented on src/components/Balance/Balance.js
> +import React, { useState, useEffect } from 'react';
удали этот файл, я этот компонент сделал и уже залил на dev

2022-01-21 09:57 UTC, maksar24 commented on src/components/Balance/Balance.module.css
> +@media screen and (min-width: 320px) {
удали этот файл, я этот компонент сделал и уже залил на dev

2022-01-21 09:57 UTC, maksar24 commented on src/components/Balance/index.js
> +export { default } from './Balance';
удали этот файл, я этот компонент сделал и уже залил на dev

2022-01-21 09:57 UTC, maksar24 commented on src/components/Header/Header.jsx
> +import { Link, NavLink } from 'react-router-dom';
удали этот файл, я этот компонент сделал и уже залил на dev

2022-01-21 09:57 UTC, maksar24 commented on src/components/Header/Header.module.css
> +@import url('https://fonts.googleapis.com/css2?family=Akronim&display=swap');
удали этот файл, я этот компонент сделал и уже залил на dev

2022-01-21 09:57 UTC, maksar24 commented on src/components/Header/animationKeyframes.css
> +/* @keyframes Blazing {
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/components/Header/index.js
> +export { default } from './Header';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/components/OnLoader/OnLoader.js
> +import React from 'react';
удали файл, я создам loader

2022-01-21 09:57 UTC, maksar24 commented on src/components/OnLoader/index.js
> +export { default } from './OnLoader';
удали файл, я создам loader

2022-01-21 09:57 UTC, maksar24 commented on src/components/PrivateRoute.js
> +import React from 'react';
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/components/PublicRoute.js
> +import React from 'react';
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/components/UserLogout/UserLogout.jsx
> +import { useState } from 'react';
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/components/UserLogout/UserLogout.module.css
> +.logoutBtn {
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/components/UserLogout/index.js
> +export { default } from './UserLogout';
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/hooks/useOnClickOutside.js
> +import { useEffect } from 'react';
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/hooks/useWindowDimensions.js
> +import { useState, useEffect } from 'react';
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/bcgImage.svg
> +<svg width="1270" height="232" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M89 104.347c0 3.974-.86 7.874-2.58 11.67a72.894 72.894 0 0 1-7.237 12.5 5.63 5.63 0 0 1-.393.485l3.39 4.211a.886
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/ArrowToGoBack.svg
> +<svg width="18" height="12" fill="none" xmlns="http://www.w3.org/2000/svg">
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/Group.svg
> +<svg width="18" height="18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17.659 7.334c.078 0 .141.065.141.145V9c0 .57-.051 1.126-.15 1.666-.766 4.194-4.375 7.364-8.7 7.334C4.097 17.965.21
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/Union.svg
> +<svg width="183" height="47" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="m8.688 26.535 3.565-3.91 7.673 13.416h10.298l-12.179-20.1L30.224 0H19.48l-
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/Vector.svg
> +<svg width="83" height="89" fill="none" xmlns="http://www.w3.org/2000/svg">
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/bcgImageBottom.svg
> +<svg width="183" height="142" fill="none" xmlns="http://www.w3.org/2000/svg">
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/crown-down.svg
> +<svg width="12" height="7" fill="none" xmlns="http://www.w3.org/2000/svg">
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/crown-up.svg
> +<svg width="12" height="7" fill="none" xmlns="http://www.w3.org/2000/svg">
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/edit.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 226 226">
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/logOutSprite.svg
> +<svg aria-hidden="true" style="position:absolute;width:0;height:0;overflow:hidden" xmlns="http://www.w3.org/2000/svg"><defs>
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/logo.svg
> +<svg width="90" height="31" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="6" y="5" width="33" height="26" rx="8" fill="#FB7C2F"/><rect width="33" height="26" rx="8" fill="#FB7C2F" fill-opac
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/img/svg/report.svg
> +<svg width="14" height="14" fill="none" xmlns="http://www.w3.org/2000/svg">
удали файл

2022-01-21 09:57 UTC, maksar24 commented on src/index.css
> +html {
удали все с этого файла и найди такой файл у нас в репозитории и скопируй все содержимое и вставь сюда

2022-01-21 09:57 UTC, maksar24 commented on src/index.js
> +import 'modern-normalize/modern-normalize.css';
с это по 8ю строку удали

2022-01-21 09:57 UTC, maksar24 commented on src/index.js
> +import { store, persistor } from './redux/store';
эту строку тоже удали

2022-01-21 09:57 UTC, maksar24 commented on src/index.js
> +    <Provider store={store}>
удали все что между <React.StrictMode> и вставь туда просто <App />

2022-01-21 09:57 UTC, maksar24 commented on src/redux/auth/auth-actions.js
> +import { createAction } from '@reduxjs/toolkit';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/auth/auth-operations.js
> +import Alert from '../../components/Alert';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/auth/auth-reducer.js
> +import { combineReducers } from 'redux';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/auth/auth-selector.js
> +const getIsAuthenticated = state => state.auth.isLogin;
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/auth/index.js
> +export * from './auth-actions';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/store.js
> +import { configureStore, getDefaultMiddleware } from '@reduxjs/toolkit';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/transactions/index.js
> +export * from './transactions-actions';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/transactions/transactions-actions.js
> +import { createAction } from '@reduxjs/toolkit';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/transactions/transactions-operations.js
> +import * as actions from './transactions-actions';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/transactions/transactions-reducers.js
> +import { createReducer, combineReducers } from '@reduxjs/toolkit';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/redux/transactions/transactions-selectors.js
> +const getTotalBalance = state => state.wallet.totalBalance;
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/routes.js
> +const routes = {
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/services/fetchApi.js
> +import axios from 'axios';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/components/Alert/Alert.js
> +import Swal from 'sweetalert2';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on src/components/Alert/index.js
> +export { default } from './Alert';
удали этот файл

2022-01-21 09:57 UTC, maksar24 commented on package.json
>    "dependencies": {
вместо своего "dependecies" вставь вот этот 
"dependencies": {
    "@datepicker-react/hooks": "^2.8.4",
    "@reduxjs/toolkit": "^1.7.1",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^0.25.0",
    "chart.js": "^3.7.0",
    "modern-normalize": "^1.1.0",
    "react": "^17.0.2",
    "react-chartjs-2": "^4.0.0",
    "react-datepicker": "^4.6.0",
    "react-dom": "^17.0.2",
    "react-icons": "^4.3.1",
    "react-media": "^1.10.0",
    "react-redux": "^7.2.6",
    "react-router-dom": "^6.2.1",
    "react-scripts": "5.0.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.1",
    "web-vitals": "^2.1.3",
    "gsap": "^3.9.1"
  },

2022-01-23 20:49 UTC, maksar24 approved these changes

2022-01-23 20:49 UTC, merged